name: ptyrad
channels:
  - pytorch
  - conda-forge
dependencies:
  - accelerate
  - h5py
  - jupyter
  - matplotlib
  - optuna
  - python>=3.10,<3.13
  - pytorch>=2.0,<2.7
  - scikit-learn
  - scipy
  - tifffile
  - torchvision

# Capping at 2nd newest versions of Python and PyTorch as of 2025.05.19 just to be preventive.